import type { ScrapingSource } from "../types.js";

export const scrapingSources: ScrapingSource[] = [
  {
    id: "aguiar-arcor-resistencia",
    storeName: "Aguiar Resistencia",
    storeType: "mayorista",
    city: "Resistencia",
    searchUrlTemplate: "https://aguiares.com/",
    requiresJavascript: false,
    enabled: false,
    disabledKind: "requires_login",
    disabledReason:
      "Distribuidor oficial Arcor local; la compra online se realiza por Tokin y requiere login B2B.",
  },
  {
    id: "granashop-resistencia",
    storeName: "Granashop Resistencia",
    storeType: "minorista",
    city: "Resistencia",
    searchUrlTemplate: "https://granashop.mitiendanube.com/search/?q={query}",
    requiresJavascript: false,
    selectors: {
      productCard: ".js-item-product, .item-product, .product-item",
      name: ".js-item-name, .item-name, .product-title",
      price: ".js-price-display, .price, .item-price",
      image: "img",
      link: "a[title], .js-item-name",
    },
  },
  {
    id: "maxiconsumo-web-referencia",
    storeName: "Maxiconsumo Web (referencia sin login)",
    storeType: "mayorista",
    city: "Resistencia",
    searchUrlTemplate:
      "https://maxiconsumo.com/sucursal_chaco/catalogsearch/result/?q={query}",
    requiresJavascript: false,
    selectors: {
      productCard: "li.product-item",
      name: "a.product-item-link",
      price: ".price-box.highest .price, .price-box .price",
      image: ".product-item-photo img",
      link: "a.product-item-link",
    },
  },
  {
    id: "yaguar-chaco-ofertas",
    storeName: "Yaguar Chaco Ofertas",
    storeType: "mayorista",
    city: "Resistencia",
    searchUrlTemplate: "https://yaguar.com.ar/chaco/",
    requiresJavascript: false,
    catalogSearchMode: "full_page",
    maxCards: 120,
    selectors: {
      productCard: ".yaguar-producto-card",
      name: ".yaguar-producto-titulo",
      price: ".yaguar-producto-precio",
      image: ".yaguar-producto-imagen img",
    },
  },
  {
    id: "vital-chaco",
    storeName: "Supermayorista Vital Chaco",
    storeType: "mayorista",
    city: "Resistencia",
    searchUrlTemplate: "https://tiendaonline.vital.com.ar/search?text={query}",
    requiresJavascript: true,
    enabled: false,
    disabledKind: "requires_login",
    disabledReason:
      "La tienda online redirige la busqueda a login; requiere cuenta para consultar catalogo/precios.",
  },
  {
    id: "sorpresas-distribuidora-golda",
    storeName: "Sorpresas SAS / Distribuidora Golda",
    storeType: "mayorista",
    city: "Resistencia",
    searchUrlTemplate: "https://sorpresas.com.ar/",
    requiresJavascript: true,
    enabled: false,
    disabledKind: "no_public_prices",
    disabledReason:
      "Publica catalogo de rubros en GPedidos, pero los precios no quedan expuestos publicamente para comparar.",
  },
  {
    id: "goloso-resistencia",
    storeName: "Goloso Mayorista Integral de Golosinas",
    storeType: "mayorista",
    city: "Resistencia",
    searchUrlTemplate: "https://miguiaargentina.com.ar/empresas/goloso.html",
    requiresJavascript: false,
    enabled: false,
    disabledKind: "no_public_catalog",
    disabledReason:
      "Mayorista local de golosinas identificado, pero no expone catalogo publico con precios para scraping.",
  },
  {
    id: "el-popular-mayorista",
    storeName: "El Popular Mayorista",
    storeType: "mayorista",
    city: "Resistencia",
    searchUrlTemplate: "https://elpopularmayorista.com.ar/",
    requiresJavascript: false,
    enabled: false,
    disabledKind: "no_public_prices",
    disabledReason:
      "Mayorista local con ofertas por WhatsApp y sitio institucional; no expone catalogo publico con precios producto por producto.",
  },
  {
    id: "distribuidora-america",
    storeName: "Distribuidora America",
    storeType: "mayorista",
    city: "Resistencia",
    searchUrlTemplate: "https://www.distribuidoraamerica.com.ar/tienda",
    requiresJavascript: true,
    enabled: false,
    disabledKind: "out_of_scope",
    disabledReason:
      "La tienda online publica productos, pero no corresponde al rubro de marcas alimenticias objetivo.",
  },
  {
    id: "cheek-sa",
    storeName: "Supermercado Mayorista CHEEK S.A.",
    storeType: "mayorista",
    city: "Resistencia",
    searchUrlTemplate: "https://es.cybo.com/AR-biz/supermercado-mayorista-cheek-s-a_1f",
    requiresJavascript: false,
    enabled: false,
    disabledKind: "no_public_catalog",
    disabledReason:
      "No se encontro un catalogo online publico vigente con buscador y precios.",
  },
];
